version: '3'

services:
  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - 5000:3000
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    env_file:
      - .env.development
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:11.1-alpine
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    env_file:
      - .env.development
