default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost'} %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development:
  <<: *default
  database: private_journal_development

test:
  <<: *default
  database: private_journal_test

production:
  <<: *default
  database: private_journal_production
  username: private_journal
  password: <%= ENV['PRIVATE_JOURNAL_DATABASE_PASSWORD'] %>
